logging:
  level:
    root: INFO
    by.javaguru: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
keycloak:
  hostname: http://localhost:8080
  realm: profiler

spring:
  application:
    name: IDENTITY-SERVICE
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: keycloak-service
            client-secret: iDQhobCnQHCF00R5Ye3a3MSkRLUvbPTA
            scope: openid
            authorization-grant-type: password
        provider:
          keycloak:
            issuer-uri: ${keycloak.hostname}/realms/${keycloak.realm}


server:
  port: 8311
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
