jwt:
  secret-key: Ti1MMkRsVEd3Qkt5dVJMMlNLWXo4LWE2SVkwUG90MnZpdUhyRUlzQ0xtbz0=
  expiration-time: 1800000

logging:
  level:
    root: INFO
    com.example: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

spring:
  application:
    name: IDENTITY-SERVICE
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
      url: jdbc:h2:mem:db
      username: sa
      password:
      driver-class-name: org.h2.Driver

server:
  port: 8311
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
