server:
  port: 8314

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  h2:
    console.enabled: true
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: INDUSTRY-SERVICE
  datasource:
    url: jdbc:h2:mem:db
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jackson:
    deserialization:
      fail-on-unknown-properties: true

