logging:
  level:
    org.springframework.security: TRACE

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: GATEWAY
  cloud:
    gateway:
      routes:
        - id: experience-service
          uri: lb://EXPERIENCE-SERVICE
          predicates:
            - Path=/api/v1/experience/**

        - id: industry-service
          uri: lb://INDUSTRY-SERVICE
          predicates:
            - Path=/api/v1/industry/**

        - id: identity-service
          uri: lb://IDENTITY-SERVICE
          predicates:
              - Path=/auth/**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/profiler

server:
  port: 8310