server:
  port: 8888
spring:
  application:
    name: config-repo
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ShadowOfEnmity/config-repo.git
          default-label: main
          search-paths:
            - GATEWAY